Add compressed JS code
hanami/ujs pull request #1
Opened 2018-01-27 22:06 UTC by marionschleifer

I put the contents of these files
https://github.com/hauleth/vanilla-ujs/tree/master/lib/assets/javascripts/vanilla-ujs
into one file for Hanami, as compressed JavaScript.

2018-01-30 08:17 UTC, jodosha requested changes
@marionschleifer Thanks for this PR.

I'd make a few changes:

  1. instead of having it under `lib/hanami/ujs/ujs.js` can we move it under `lib/hanami/ujs/assets/javascripts/ujs.js`? This is for symmetry with other Hanami plugin gems that want to ship assets.

  1. Add the original files here into the repository in a directory like `vendor/vanilla-ujs`.

  1. Document the `vanilla-ujs` version used. When they will release a new version, we know that we should do it too.

  1. Document and automatize (if possible) the process of compressing the JS code. A Rake task or a Bash script are great tools to use in this case. I can do this, if you want.

  1. Add a copyright notice, by mentioning `vanilla-ujs`, their authors and their License.

2018-02-06 19:07 UTC, cllns commented
Can we add newlines to the ends of all the files? This should work: https://unix.stackexchange.com/a/31955

And here's a little context and tells you how to make it so your editor will do this automatically: https://robots.thoughtbot.com/no-newline-at-end-of-file :)

2018-02-11 17:58 UTC, marionschleifer commented
@jodosha done!
@cllns done!
😄

2018-02-12 10:49 UTC, jodosha approved these changes

2018-02-12 10:50 UTC, merged